name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.19.4
        # Path to the go.mod or go.work file.
        #go-version-file: # optional
        # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
        #check-latest: # optional
        # Used to pull node distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
        #token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
        # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
        cache: false
        # Used to specify the path to a dependency file - go.sum
        #cache-dependency-path: # optional
        # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
        architecture: x64
        
    - name: setup-docker
        # You may pin to the exact commit or the version.
        # uses: docker-practice/actions-setup-docker@9fafeb38361d5d48e5afc207293715e023b6cfe0
      uses: docker-practice/actions-setup-docker@1.0.9

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
